### ISSUE TITLE
create a login page

### ISSUE THREAD

**Issue by Rosh-Q** [Rosh-Q/Pixcel#10]
no need for the functionality

**Comment by AvineshTripathi** [comment]
Assign me this please

**Comment by Rosh-Q** [comment]
sure @AvineshTripathi

**Comment by AvineshTripathi** [comment]
Will be using material ui is that ok ? @Rosh-Q

**Comment by thesahindia** [comment]
@AvineshTripathi you can use semantic ui. we are using semantic ui for styling.

**Comment by Rosh-Q** [comment]
@AvineshTripathi you have to use semantic-ui. @thesahindia is working on sign up page and we don't want to use two different type of styling for signup and login page. Both pages need to be similar.

**Comment by AvineshTripathi** [comment]
hey @Rosh-Q I am getting error in the set up of semantic ui
![Screenshot from 2021-10-06 16-27-26](https://user-images.githubusercontent.com/73980067/136190399-a290a30b-66d5-4437-94a2-bcb6d8097712.png)
![Screenshot from 2021-10-06 16-27-30](https://user-images.githubusercontent.com/73980067/136190411-6cfe70e8-4d6f-4e5b-b851-27794d0acc86.png)

**Comment by AvineshTripathi** [comment]
damn missed that
