### ISSUE TITLE
fetch some default results on homepage

### ISSUE THREAD

**Issue by Rosh-Q** [Rosh-Q/Pixcel#4]
Currently we have to search for the images but we need some default results on homepage.

**Comment by angelinjohn** [comment]
Hi,I would like to contribute to this issue

**Comment by Rosh-Q** [comment]
Go ahead @angelinjohn

**Comment by Pongy-jr** [comment]
Hi, I would love to contribute to this issue.

**Comment by Rosh-Q** [comment]
closing the issue as this issue got fixed by @thesahindia 's PR
