### ISSUE TITLE
Create a sign up page

### ISSUE THREAD

**Issue by Rosh-Q** [Rosh-Q/Pixcel#9]
no need for the functionality

**Comment by thesahindia** [comment]
assign this to me.

**Comment by thesahindia** [comment]
Hi @AvineshTripathi you can see the code here 548eb35fe9beadfb5f5514b96a82a96ac61d6899

**Comment by thesahindia** [comment]
@AvineshTripathi
![ss](https://user-images.githubusercontent.com/83179295/136206258-0a287cde-0eb5-47ca-9e65-6e6aa4b69ceb.png)

**Comment by thesahindia** [comment]
Sure @AvineshTripathi. By the way I was thinking about swapping our tasks would you like to work on user profile issue? Can we do it @Rosh-Q?

**Comment by Rosh-Q** [comment]
@thesahindia  yeah sure why not. I will assign @AvineshTripathi for that issue and @thesahindia you work on login page.
